version: '3.9'
services:
    frontend:
        build: ./client
        ports:
            - 3000:3000
        environment:
            API: http://localhost:5002/graphql
    backend:
        build: ./server
        ports:
            - 5002:5002